name: testenv
channels:
  - conda-forge
dependencies:
- python=3
- numpy
- scipy
- pandas
- beautifulsoup4
- gdal
- geos
- fiona
- shapely
- pyproj
- gcc
- cython
- libspatialindex
- rtree
- jinja2
- geopandas
- pip!=10
- pip:
    - coveralls
    - pytest-cov
    - python-coveralls